### ISSUE TITLE
Documentation Update / Issue Tracker Cleaning

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#506]
I'm aiming to update some documentation hopefully in time for the 0.12.6 push and subsequently when I'll be covering Rcpp in class.
# Documentation Specific Issues

The issues that I am looking to resolve are:
- [x] #484 opened on May 29 _Rcpp-quickrefs issue_
- [x] #460 opened on Apr 12 _Long vector Rcpp function fails on Windows server, C function works_
- [x] #419 opened on Jan 14 _Strange behavior with CharacterVector and std::sort_
- [x] #418 opened on Jan 13 _Document default arguments in Rcpp FAQ_
- [x] #416 opened on Jan 13 _Add documentation for RCPP_EXPOSED_AS and similar macros in the vignette_
- [ ] #317 opened on Jun 30, 2015 _Coding Standards note ?_
- [ ] #268 opened on Feb 26, 2015 _Problem with automatic RNG scoping_
- [ ] #56 opened on Nov 15, 2013 _Convert uses of inline::cxxfunction to attributes._

Outside of the above issues I will also try to do the following:
- [x] 1. #524 Introduce an "Rcpp beginners" vignette to serve as an "Rcpp Introductory" vignette
- [x] ~~2. Move the current "Rcpp Introduction" to "Rcpp JSS Paper" as the present title is a bit misleading [per SO](http://stackoverflow.com/questions/38399935/how-to-use-a-c-wrapper-in-r-via-rcpp).~~
- [x] ~~3. #604 Try to switch the present vignettes over to use `knitr` or `rmarkdown` if there is no objection. Principal motivation for this change is due to the present way being a bit adhoc and non-standard with respect to `highlight`.~~

# Closing Issues

Lastly, depending on time, I'm going to try to bring the issue tracker up to date by finding the resolution to associated issues via PRs or git commits and asking that those issues are closed. 

## Items completed, but not closed
- [x] #426 opened on Jan 18 _Rcpp::algorithm proposal_
- [x] #321 opened on Jul 6, 2015 _Underlying CHARSXP in String class needs gc protection_
- [x] #277 opened on Mar 15, 2015 _Rcpp 0.11.5 test failures with new Rtools toolchain_
- [x] #272 opened on Mar 9, 2015  _Macros like 'major' still leak, or are protected too aggressively_
- [x] #223 opened on Jan 2, 2015 _Sugar var() only knows numeric_
- [x] #183 opened on Sep 23, 2014 _ListOf<>::names() and ::attr()_
- [x] #177 opened on Sep 13, 2014 _`bool` not converted to `LogicalVector` as expected_
- [ ] #170 opened on Aug 30, 2014 _Two constructors of Vector class not meaningful_
- [x] #165 opened on Aug 8, 2014 _Rcpp-extending: implementing Rcpp:wrap() for a templated type_
- [x]  #145 opened on May 18, 2014  _.parseLinkingTo fails with versioned LinkingTo_
- [x] #137 opened on Apr 10, 2014 _Allow user to enable/disable bounds checking_
- [x] #135 opened on Mar 18, 2014 _ListOf<T> class_
- [x] #130 opened on Mar 13, 2014 _Attributes vignette and Imports/Depends distinction_
- [x] #129 opened on Mar 13, 2014 _Matrix default ctor does not make a matrix_
- [x] #128 opened on Mar 11, 2014 _Bug in assigning SEXP to List_
- [x] #80 opened on Nov 30, 2013 _update OSX information in FAQ vignette_
- [x] #76 opened on Nov 29, 2013 _NEWS.Rd is stale_
- [x] #75 opened on Nov 29, 2013 _ChangeLog is stale_
- [x] #69 opened on Nov 25, 2013 _checking for interupts_
- [x] #30 opened on Nov 6, 2013 _tests for automatically generated math functions_
- [x] #29 opened on Nov 6, 2013 _tests for dpq functions_
- [x] #22 opened on Nov 6, 2013 _operator/ needs to handle the case of division by 0_
- [x] #16 opened on Nov 6, 2013 _logical indexing_
- [x] #9 opened on Nov 6, 2013 _Vignette about stats function_
- [x] #6 opened on Nov 6, 2013 _Sugar ops unit tests_

## Items not completed
- [x] #308 opened on Jun 23, 2015  _Error messaging suggestion_
  - Support presently exists for GCC 4.6.2 <= in the code base and given the nature of R's RHEL component, it is inadvisable to trigger a warning within _Rcpp_. Best to let it play out on required code bases (e.g. `RcppArmadillo`).
- [x] #229 opened on Jan 16, 2015 _Rcpp::SquareMatrix class_
  - No desire to support a square matrix class without accompanying algorithms
- [x] #37 opened on Nov 7, 2013 _More flexible attributes_
  - Project to abstract away attributes has been moved to a new location

# Quick code fixes
- [x] #526 opened on Aug 1 _Autogeneration Warning for RcppExports._
- [x] #387 opened on Oct 30, 2015 _Fix invalid C++ identifiers_
- [x] #326 opened on Jul 17, 2015 _Environment::(get,find)( Symbol )_
- [x] #28 opened on Nov 6, 2013 _tests for random generators_

# Possible future code projects
- #170 opened on Aug 30, 2014 _Two constructors of Vector class not meaningful_
  - Remark: The two constructors are still in place to save:`CharacterVector x = std::string("hello");` could this feature be deprecated in favor of `::create()`? 
- #6 opened on Nov 6, 2013 _Sugar ops unit tests_
  - Remark: Possible feature: Matrix Multiplication (perhaps use the `%` operator for element-wise manipulation similar to `armadillo`?) and Matrix to Matrix Addition.

**Comment by jjallaire** [comment]
With respect to switching to knitr/rmarkdown, you should note that the development version of knitr now handles caching of Rcpp chunks correctly, see http://rmarkdown.rstudio.com/authoring_knitr_engines.html#rcpp

**Comment by eddelbuettel** [comment]
Regarding:

- point 2: I was about to do it but then relented -- we have a _ton_ of advice out there saying 'start by  `vignette("Rcpp-introduction")`' so I no longer think we want that.

- point 3: I am not sure I am in favour of a wholesale replacement of pdf by html.  I like both very much and still think pdf vignette render much better and generally look better so I think there is room to keep pdf 

- point 1: contributed documentation is always welcome, I'd be happy to help / get involved as we discussed.

**Comment by jjallaire** [comment]
Switching to rmarkdown could still preserve pdf output. If we wanted full
control of the LaTex (i.e. identical appearance to current vignettes) we
could even create an rcpp_vignette custom format)

**Comment by eddelbuettel** [comment]
Quite true on `.md` to `.pdf` as a process which is in fact what I do often.  But having written the book I can assert that dealing with nine vignettes and rewriting them is not a small task, and if anybody can muster that much energy then maybe we should focus the energy somewhere else?  _In principle_ this can be done -- and replacing use of `highlight` by `pandoc` would be nice.  In practice I have some doubts.    As for a custom vignette format which looks good in pdf _and_ html, I'd be a taker.  We don't have that now, do we?  (I not to beat a dead horse but current bookdown output is far from stylish too...)

**Comment by coatless** [comment]
* On point 2: Wouldn't that make it better to proceed with the change once the beginners vignette is ready? I ask since that is where the flock of users are going to initially. The alternative is probably naming the beginners vignette more as a Quick Start
* On point 3: I agree that it is labour intensive. Perhaps, let's do a slight demo with one of the smaller vignettes?

**Comment by eddelbuettel** [comment]
- point 2: come to think about it, _once we have a new vignette with an intro_, we can have it _provide_ the `Rcpp-introduction` target and rename the current one to `Rcpp-jsspaper`.  That intro could even be a quick two-paper with a quick start example and a pointer for further references.
- point 3: Oh yes. We should just pick.  Or start with the intro.

Come to think about it, we can clearly have a nice new Rcpp-intro (in markdown, and possibly with output in pdf and html as @jjallaire volunteered :smile_cat: a new style file) for 0.12.7 in two months.

**Comment by coatless** [comment]
@eddelbuettel Any chance I could squeeze the *beginners* vignette into the 0.12.6 release? More specifically, do you have a date in mind for 0.12.6 release? I ask because I will hopefully have the two pager done by tomorrow. I'm presently working on it in between cluster runs.

**Comment by eddelbuettel** [comment]
The date is basically ... tomorrow or Monday.  So I am hesitant.  That said, this would make for an excellent candidate for 0.12.6.1 where we can test the transition to a new Rcpp-introduction.  And by being on a drat repo your students can `install.packages()` it as normal.

So in short I'd rather not ram it in.

**Comment by coatless** [comment]
@eddelbuettel Okay. Definitely agree as tomorrow/monday would be too quick of a turn around time. I was hoping for later in the week. I'll inoculate them to `drat` before `Rcpp`. 

Would you prefer a flood of completes or should I move through the items one at a time?

**Comment by eddelbuettel** [comment]
Thanks -- I am thinking an issue per item may make sense.  Maybe even just continue on the old items but keep another one (this one?) as a jumping board?

[ I recently needed a tick-off list to collect 'ok by me' replies [for digest](https://github.com/eddelbuettel/digest/issues/36) -- maybe something like that could help?  We could just prefix your nice list above...

**Comment by thirdwing** [comment]
@coatless I think we also need to document https://github.com/RcppCore/Rcpp/issues/675
